apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: test-nginx
    repoURL: 'https://github.com/xiaoya-create/argocd.git'
    targetRevision: HEAD
  sources: []
  project: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []
