apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment01
  annotations:
    prometheus.io/port: "9180"
    prometheus.io/scrape: "true"
  labels:
    app: web-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      containers:
      - name: nginx18
        image: nginx:1.8
        ports:
        - containerPort: 80
