apiVersion: v1
kind: Service
metadata:
  name: helm-nginx
  namespace: default
spec:
  type: NodePort
  selector:
    app: helm-nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30008
    protocol: TCP
